[package]
name = "bouncywm"
version = "0.1.0"
authors = ["lightning1141 <lightning1141@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11 = { version = "2.18.1", features = ["xlib"] }
